spring:
    datasource:
        url: jdbc:h2:mem:absa;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        platform: h2
        username: sa
        password:
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                show_sql: true
                use_sql_comments: false
                format_sql: true
    h2:
        console:
            enabled: true
            path: /console
            settings:
                trace: false
                web-allow-others: false
    rabbitmq:
        host: 34.205.16.148
        username: user
        password: password
app:
    endpoint:
        routingRules: http://127.0.0.1:8080/rules
    routingRule:
        id: 1

